Adminitrator = Semua.
Admin = Semua, kecuali Menu Konfigurasi.
Pimpinan = Semua, bisa melihat modul direksi saja.
Supervisor = Semua.
Rekammedis = Loket dan Rekammedis.
IGD = IGD.
Rawat Jalan = Rawat Jalan.
Laboratorium = Laboratorium.
Radiologi = Radiologi.
Kasir = Kasir.
Admission = Admission.
Rawat Inap = Rawat Inap.
<!-- Verifikasi Rawat Inap = Kasir. -->
Fisioterapi = Fisioterapi
Gizi = Gizi
Operasi = Operasi
Display = Display
Antrian = Antrian
Apotik = Apotik
logistik = logistik
